### ISSUE TITLE
Running the code fried my 12 year old laptop.

### ISSUE THREAD

**Issue by gvaldezsan** [cameronzsmith/LPTHW#1]
Tried running ex20.py but the system entered an infinite loop and destroyed my laptop, you now owe me a new laptop plus i'm suing you. Kappa.

**Comment by cameronzsmith** [comment]
Could not replicate from my end. Please mail me the laptop to my home address so that I can try and replicate it from my end.

**Comment by gvaldezsan** [comment]
Unfortunately it blew into a bazillion pieces, destroying part of my neighbor's house in the process (he will be suing too btw) but we could try replicating with my toaster. I'll just need you to send the mail cost of 2,500 to my friend the Nigerian prince

**Comment by cameronzsmith** [comment]
I'll see you and your neighbor in court.

**Comment by gvaldezsan** [comment]
You'll never silence me!
